=== cedric-cnam/neuma/static/json/dmos/schema/dmos_system.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "dmos_system.json",
  "title": "Schema of system descriptor",
  "description": "Each system is a list of headers, one for each staff, and a list of measures",
  "type": "object",
  "properties": {
      "id" : {"description": "System id", "type": "integer"},
     "region": {"description": "Region covered by the system in the page","$ref": "dmos_region.json"},
    "headers": {
         "type": "array",
          "items": {"$ref": "dmos_staff_header.json" }
    },
    "measures": {
         "type": "array",
         "items": {"$ref": "dmos_measure.json" },
           "minItems": 1
    }
  },
   "required": ["id", "region", "headers", "measures"],
  "additionalProperties": false
}

=== cedric-cnam/neuma/static/json/dmos/data/ex1/page1_s1.json
{
 "id": 1,
 "region": [[0,0], [0,0],[0,0]],
 "headers": [
    {"id_part": "P0", "no_staff":  0, "first_bar": [[0,0], [0,0]]},
    {"id_part": "P1", "no_staff": 1},
    {"id_part": "P2", "no_staff": 2}
  ],
 "measures": [
      {"$ref": "page1_s1_m1.json"},
      {"$ref": "page1_s1_m2.json"},
      {"$ref": "page1_s1_m3.json"}
  ]
}
